### ISSUE TITLE
Documentation...

### ISSUE THREAD

**Issue by hi5kba** [QasimK/mal-scraper#21]
i can't seem to find any mention of what OS  or Environment this needs to run on or its dependencies needed to install.
i do have the capability to run any OS as my PC is pretty much Virtualised. so which is best?
secondly is there a mode that will download *All Anime (inc. OVA, Specials, Movies etc)?

**Comment by QasimK** [comment]
Hi @hi5kba. This is a pure Python library with no dependencies so it can be run in any environment.
